language: node_js
node_js:
  - "stable"
install: npm install
cache:
  directories:
  - node_modules
script:
  - npm run start:test
env: 
  - process.env.SECRET_KEY=secret_key
after_success: npm run start:coverage
