services:
 - postgresql
addons:
 postgresql: "9.6"
language: node_js
node_js:
  - "stable"
install: npm install
cache:
  directories:
  - node_modules
before_script:
 - psql -c 'create database mydiary;' -U postgres
script:
  - npm run start:test
env: 
  - process.env.SECRET_KEY=secret_key
after_success: npm run start:coverage
